// server/mail.js
const express = require("express");
const cors = require("cors");
const nodemailer = require("nodemailer");


const app = express();
app.use(cors());
app.use(express.json());

app.post("/send-mail", async (req, res) => {
  const { name, email, message } = req.body;

  const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: "pymailproj@gmail.com",
      pass: "flpv ffsv ufwh xgsu", 
    },
  });

const mailOptions = {
  from: email,
  to: "pymailproj@gmail.com",
  subject: `New Contact Form Submission from ${name}`,
  html: `
<div style="font-family: Arial, sans-serif; padding: 20px; border: 1px solid #ddd; border-radius: 8px;">
  <h2 style="color: #2c3e50;">New Contact Form Message</h2>

  <p style="font-size: 15px;">
    <strong>Name:</strong> ${name}
  </p>

  <p style="font-size: 15px;">
    <strong>Email:</strong> ${email}
  </p>

  <p style="font-size: 15px; margin-top: 20px;">
    <strong>Message:</strong><br>
    <div style="white-space: pre-wrap; margin-top: 10px; padding: 12px; background: #f7f7f7; border-left: 4px solid #3498db;">
${message}
    </div>
  </p>

  <hr style="margin-top: 25px;">
  <p style="font-size: 12px; color: #888;">
    This email was automatically generated by your website contact form.
  </p>
</div>
  `,
};



  try {
    await transporter.sendMail(mailOptions);
    res.status(200).json({ success: true, msg: "Mail sent" });
  } catch (err) {
    res.status(500).json({ success: false, msg: "Mail failed", error: err });
  }
});

app.listen(5000, () => console.log("Mail server running on port 5000"));
